all: circleArea upperCase bubbleSort primeTime typeOfChar primeFactor swapPointers minimum sortArray cars threads

clean:
	rm -f *.o *~ circleArea upperCase bubbleSort primeTime typeOfChar primeFactor swapPointers minimum sortArray cars threads threads

circleArea: circleArea.c
	gcc circleArea.c -g -F dwarf -o circleArea

upperCase: upperCase.c
	gcc upperCase.c -g -F dwarf -o upperCase

bubbleSort: bubbleSort.c
	gcc bubbleSort.c -g -F dwarf -o bubbleSort

primeTime: primeTime.c
	gcc primeTime.c -g -F dwarf -o primeTime

typeOfChar: typeOfChar.c
	gcc typeOfChar.c -g -F dwarf -o typeOfChar

primeFactor: primeFactor.c
	gcc primeFactor.c -g -F dwarf -o primeFactor

swapPointers: swapPointers.c
	gcc swapPointers.c -g -F dwarf -o swapPointers

minimum: minimum.c
	gcc minimum.c -g -F dwarf -o minimum

sortArray: sortArray.c
	gcc sortArray.c -g -F dwarf -o sortArray

cars: cars.c
	gcc cars.c -g -F dwarf -o cars

threads: threads.c
	gcc threads.c -g -lm -lpthread -F dwarf -o threads
