all: circleArea upperCase bubbleSort primeTime

clean:
	rm -f *.o *~ circleArea upperCase bubbleSort primeTime

circleArea: circleArea.c
	gcc circleArea.c -g -F dwarf -o circleArea

upperCase: upperCase.c
	gcc upperCase.c -g -F dwarf -o upperCase

bubbleSort: bubbleSort.c
	gcc bubbleSort.c -g -F dwarf -o bubbleSort

primeTime: primeTime.c
	gcc primeTime.c -g -F dwarf -o primeTime
